In [115]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<font size="5" color="black">ch14_웹 데이터 수집_2</font>
***
# 1. Selenium
- [selenium](https://selenium-python.readthedocs.io/)을 이용한 동적 웹크롤링
- `pip install selenium`

* selenium - 4.47.0 / requests - 2.34.2 / urllib3 - 2.7.0

In [2]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

In [10]:
dv = webdriver.Chrome() #새로운 크롬창 생성
dv.get("http://www.python.org") # 생성한 창에 url 삽입

In [11]:
# 페이지 제목에 "Python"이라는 단어가 포함되어 있는지 확인
assert "Python" in dv.title

In [12]:
# 검색창 입력 필드(name="q") 검색 - By.CLASS_NAME, By.ID, By.CSS_SELETOR, By.TAG_NAME 등
el = dv.find_element(By.NAME, "q")

In [7]:
el.clear() # 입력 필드 clear
el.send_keys("pycon") # input box에 pycon 삽입
el.send_keys(Keys.RETURN) # 엔터(Return) 입력으로 검색 시행

In [13]:
el.send_keys(Keys.CONTROL, "a") # ctrl + a 입력 (입력 필드 내 전체 선택)
el.send_keys('pycon')
btn_el = dv.find_element(By.CSS_SELECTOR, 'button#submit')
btn_el.click()

In [18]:
result_list = dv.find_elements(By.CSS_SELECTOR, 'li>h3>a')
for result in result_list:
    print('{} - {}'.format(result.text, result.get_attribute('href')))

PSF PyCon Trademark Usage Policy - https://www.python.org/psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - https://www.python.org/events/python-events/378/
PyCon Australia 2013 - https://www.python.org/events/python-events/57/
PyCon AU 2019 - https://www.python.org/events/python-events/776/
PyCon NL 2025 - https://www.python.org/events/python-events/2084/
PyCon Australia 2014 - https://www.python.org/events/python-events/10/
PyCon Ireland 2012 - https://www.python.org/events/python-events/76/
PyCon Ireland 2016 - https://www.python.org/events/python-events/429/
PyCon Ireland 2022 - https://www.python.org/events/python-events/1320/
PyCon Australia 2014 - https://www.python.org/events/python-events/1447/
PyCon Ireland 2023 - https://www.python.org/events/python-events/1568/
PyCon Ireland 2024 - https://www.python.org/events/python-events/1862/
PyCon APAC 2025 - https://www.python.org/events/python-events/1879/
PyCon AU 2018 - https://www.python.org/events/python-events/696/
PyCon APAC 2022 - https://www.python.org/events/python-events/1216/
PyCon PH 2024 - https://www.python.org/events/python-events/1661/
PyCon MY 2015 - https://www.python.org/events/python-events/313/
PyCon Ireland 2015 - https://www.python.org/events/python-events/333/
PyCon PL 2014 - https://www.python.org/events/python-events/191/
PyCon AU 2015 - https://www.python.org/events/python-events/273/

In [25]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(dv.page_source, 'html.parser')
result_list = soup.select('li>h3>a')
for result in result_list:
    print('{} - https://www.python.org{}'.format(result.text, result.attrs.get('href')))

PSF PyCon Trademark Usage Policy - https://www.python.org/psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - https://www.python.org/events/python-events/378/
PyCon Australia 2013 - https://www.python.org/events/python-events/57/
PyCon AU 2019 - https://www.python.org/events/python-events/776/
PyCon NL 2025 - https://www.python.org/events/python-events/2084/
PyCon Australia 2014 - https://www.python.org/events/python-events/10/
PyCon Ireland 2012 - https://www.python.org/events/python-events/76/
PyCon Ireland 2016 - https://www.python.org/events/python-events/429/
PyCon Ireland 2022 - https://www.python.org/events/python-events/1320/
PyCon Australia 2014 - https://www.python.org/events/python-events/1447/
PyCon Ireland 2023 - https://www.python.org/events/python-events/1568/
PyCon Ireland 2024 - https://www.python.org/events/python-events/1862/
PyCon APAC 2025 - https://www.python.org/events/python-events/1879/
PyCon AU 2018 - https://www.python.org/events/python-events/696/
PyCon APAC 2022 - https://www.python.org/events/python-events/1216/
PyCon PH 2024 - https://www.python.org/events/python-events/1661/
PyCon MY 2015 - https://www.python.org/events/python-events/313/
PyCon Ireland 2015 - https://www.python.org/events/python-events/333/
PyCon PL 2014 - https://www.python.org/events/python-events/191/
PyCon AU 2015 - https://www.python.org/events/python-events/273/

In [30]:
from urllib.parse import urlparse
now_url = dv.current_url
print('현재 url :', now_url)
parsedUrl = urlparse(now_url)
print('파싱 url :', parsedUrl)
domain = f'{parsedUrl.scheme}://{parsedUrl.netloc}'
print('도메인 :', domain)

현재 url : https://www.python.org/search/?q=pycon&submit=
파싱 url : ParseResult(scheme='https', netloc='www.python.org', path='/search/', params='', query='q=pycon&submit=', fragment='')
도메인 : https://www.python.org

In [31]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(dv.page_source, 'html.parser')
result_list = soup.select('li>h3>a')
for result in result_list:
    print('{} - {}'.format(result.text, domain+result.attrs.get('href')))

PSF PyCon Trademark Usage Policy - https://www.python.org/psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - https://www.python.org/events/python-events/378/
PyCon Australia 2013 - https://www.python.org/events/python-events/57/
PyCon AU 2019 - https://www.python.org/events/python-events/776/
PyCon NL 2025 - https://www.python.org/events/python-events/2084/
PyCon Australia 2014 - https://www.python.org/events/python-events/10/
PyCon Ireland 2012 - https://www.python.org/events/python-events/76/
PyCon Ireland 2016 - https://www.python.org/events/python-events/429/
PyCon Ireland 2022 - https://www.python.org/events/python-events/1320/
PyCon Australia 2014 - https://www.python.org/events/python-events/1447/
PyCon Ireland 2023 - https://www.python.org/events/python-events/1568/
PyCon Ireland 2024 - https://www.python.org/events/python-events/1862/
PyCon APAC 2025 - https://www.python.org/events/python-events/1879/
PyCon AU 2018 - https://www.python.org/events/python-events/696/
PyCon APAC 2022 - https://www.python.org/events/python-events/1216/
PyCon PH 2024 - https://www.python.org/events/python-events/1661/
PyCon MY 2015 - https://www.python.org/events/python-events/313/
PyCon Ireland 2015 - https://www.python.org/events/python-events/333/
PyCon PL 2014 - https://www.python.org/events/python-events/191/
PyCon AU 2015 - https://www.python.org/events/python-events/273/

In [32]:
dv.close() # 창 제거

# 2. 동적 웹데이터 수집
- 동적 웹크롤링

## 2.1 다음 뉴스 검색

In [47]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

dv = webdriver.Chrome()
dv.get("http://www.daum.net")
time.sleep(0.5) # 페이지 로드 완료까지 0.5초 대기

word = input('검색할 단어 : ')

el = dv.find_element(By.NAME, "q")
el.send_keys(word)
el.send_keys(Keys.RETURN)

time.sleep(1)

dv.find_element(By.LINK_TEXT, "뉴스").click()

검색할 단어 : 소공연장

In [54]:
# Soup 객체 사용 x
bodies = dv.find_elements(By.CSS_SELECTOR, 'div.item-title > strong.tit-g.clamp-g')

new_list = []

for body in bodies:
    a = body.find_element(By.TAG_NAME, 'a')
    title = a.text
    link = a.get_attribute('href')
    new_list.append([title, link])

In [53]:
# 페이지 이동
page_nav = dv.find_element(By.CLASS_NAME, 'inner_paging')
next_page = page_nav.find_element(By.LINK_TEXT, "3")
next_page.click()

In [45]:
# Soup 객체 사용 o

import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse

url = dv.current_url

response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

news_list = []

news_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')

for idx, item in enumerate(news_el):
    news_list.append({'no' : idx+1, 'title' : item.text, 'link' : item.attrs.get('href')})
    
rslt = news_list
    
import pandas as pd
pd.DataFrame(rslt)

,no,title,link
0,1,‘극장판 기븐 바다로’ 야노 쇼고·우치다 유우마 내한,http://v.daum.net/v/20260815074039872
1,2,"바이올리니스트 손모은, 오는 9월 내한공연",http://v.daum.net/v/20260818111332612
2,3,"라데팡스 재즈 콩쿠르 수상 손모은, 2집 기념 내한 공연",http://v.daum.net/v/20260818114057377
3,4,"극장판 기븐-바다로, 야노 쇼고·우치다 유우마 내한",http://v.daum.net/v/20260818081411065
4,5,재즈의 전설과 신성이 온다…에디 고메즈·마이클 마요 잇단 내한,http://v.daum.net/v/20260817155644535
5,6,대전MBC 초청 스페인 밀레니엄합창단 대전서 내한 공연,http://v.daum.net/v/20260818082833463
6,7,"'프리텐더' 부른 히게단, 세 번째 내한도 성공… 여전한 J-POP 열풍",http://v.daum.net/v/20260812124244462
7,8,"'유퀴즈' 크리스토퍼 놀란 ""첫 내한, 한국 팬 만나고 싶어서""",http://v.daum.net/v/20260812214849957
8,9,"'첫 내한' 크리스토퍼 놀란 감독, 유재석과 무슨 이야기 나눴나",http://v.daum.net/v/20260812160409227
9,10,"도미 앤 제이디 벡, 12월 서울 첫 단독 내한공연 개최",http://v.daum.net/v/20260812114507716

In [46]:
dv.quit()

## 2.2 다음 뉴스 페이징 처리

In [66]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

dv = webdriver.Chrome()
dv.get("http://www.daum.net")
time.sleep(0.5) # 페이지 로드 완료까지 0.5초 대기

word = input('검색할 단어 : ')

el = dv.find_element(By.NAME, "q")
el.send_keys(word)
el.send_keys(Keys.RETURN)

time.sleep(1)

dv.find_element(By.LINK_TEXT, "뉴스").click()

pages = int(input('수집할 페이지 수 : '))
time.sleep(1)

new_list = []

for page in range(1, 1+pages):
    
    bodies = dv.find_elements(By.CSS_SELECTOR, 'div.item-title > strong.tit-g.clamp-g')
    print('수집 중인 페이지 : ', page)
    for body in bodies:
        a = body.find_element(By.TAG_NAME, 'a')
        title = a.text
        link = a.get_attribute('href')
        new_list.append([title, link])
        
    time.sleep(3)
    
    page_nav = dv.find_element(By.CLASS_NAME, 'inner_paging')
    next_page = page_nav.find_element(By.LINK_TEXT, str(page+1))
    next_page.click()
    
news_df = pd.DataFrame(new_list, columns=['title', 'link'])
print('수집 완료 : news_df', news_df.shape)
display(news_df.head())

검색할 단어 : CPU
수집할 페이지 수 : 3
수집 중인 페이지 :  1
수집 중인 페이지 :  2
수집 중인 페이지 :  3
수집 완료 : news_df (30, 2)

,title,link
0,"GPU 다음은 CPU""…BofA, 서버 CPU 시장 5배 성장 전망",http://v.daum.net/v/20260818085917486
1,"""한국, HBM 말고도 기회 있다""…다시 뜨는 '미국 CPU'에 들썩",http://v.daum.net/v/20260816184509949
2,에이전틱 AI가 불러온 ‘CPU의 귀환’,http://v.daum.net/v/20260803063315929
3,"삼성자산운용, ‘KODEX 미국CPU반도체TOP10’ 상장 일주일 수익률 10%…“...",http://v.daum.net/v/20260811103710734
4,"AI 에이전트 시대 CPU '주목'…삼성운용, 'KODEX 미국CPU반도체TOP10...",http://v.daum.net/v/20260804084938218

In [67]:
dv.quit()

## 2.3 맞춤법 검사기
- 네이버 맞춤법 검사기 활용

In [68]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import time

In [89]:
dv = webdriver.Chrome()
dv.get('https://www.naver.com')
time.sleep(0.5)

el = dv.find_element(By.NAME, "query")
el.clear()
el.send_keys('맞춤법검사기')
el.send_keys(Keys.RETURN)
time.sleep(0.5)

chk = dv.find_element(By.CLASS_NAME, "txt_gray")
para = input('검사할 문장 : ')
chk.send_keys(para)
dv.find_element(By.CLASS_NAME, "btn_check").click()
time.sleep(0.5)

rslt = dv.find_element(By.CLASS_NAME, "_result_text")
print('맞춤법 교정 결과 : ', rslt.text)
dv.quit()

검사할 문장 : 분석결과 인공지능 기술은 업무효율성 향상, 비용절감, 새로운 서비스 창출등 긍정적 효과가 크게 나타났다. 하지만 일자리 감소, 개인정보 침해, 알고리즘 편향성등의 문제점도 동시에 확인되었다.
맞춤법 교정 결과 :  분석 결과 인공지능 기술은 업무 효율성 향상, 비용 절감, 새로운 서비스 창출 등 긍정적 효과가 크게 나타났다. 하지만 일자리 감소, 개인정보 침해, 알고리즘 편향성 등의 문제점도 동시에 확인되었다.

In [142]:
with open('data/ch14_맞춤법검사_전.txt', 'r', encoding='utf-8') as fp:
    text = fp.read()

ready_text_list = [] # 300자 내외의 문장 단위로 나눠진 텍스트의 list

while len(text)>=300:
    print(len(text))
    temp = text[:300]
    last_dot_index = temp.rfind('\n')
    ready_text_list.append(text[:last_dot_index+1])
    text = text[last_dot_index+1:]
ready_text_list.append(text)

1173
1025
830
596
432

In [143]:
print([read_text for read_text in ready_text_list])

['J-Pop(일본 대중음악)과 브리티시 밴드 음악은 각기 다른 문화적 배경과 음악적 유산을 바탕으로 독창적인 특징을 발전시켜 왔습니다. 두 장르 모두 강렬한 정체성과 탄탄한 팬층을 보유하고 있으며, 현대 대중음악에 커다란 영향을 미쳤습니다.\n\nJ-Pop의 주요특징\n\n', 'J-Pop은 화려하고 복잡한 화성학적 구조와 독특한 멜로디 전개가 가장 큰 특징입니다. 서구의 대중음악이 단순한 코드 진행 반복(Loop) 위에 멜로디를 얹는 경우가 많은 반면, J-Pop은 코드 진행이 매우 빈번하게 바뀌며 곡 내부에서 조바꿈(전조)이 활발하게 일어납니다. 또한 베이스라인의 움직임이 화려하여 음악 전체의 서사성을 극대화합니다.\n\n', '구조적으로는 도입부(A멜로)-전개부(B멜로)-절정부(싸비/후비)로 이어지는 극적인 구성을 선호합니다. 가사 면에서는 일상적인 감정, 청춘, 희망, 아련함 등의 정서를 세밀하게 담아내며, 애니메이션 및 게임 산업과의 강력한 연계를 통해 독자적인 미학을 구축했습니다. 록, 재즈, 디스코, 전자음악 등 다양한 장르를 일본특유의 감성으로 흡수·재해석하는 융합성 역시 J-Pop만의 강점입니다.\n\n브리티시 밴드의 주요 특징\n\n', "브리티시 밴드 음악은 1960년대 '브리티시 인베이전(British Invasion)'부터 90년대 브릿팝(Britpop)을 거쳐 현대 인디 록에 이르기가지, 대중음악사의 줄기 를 형성해 온 거대한 흐름입니다. 특유의 서늘하면서도 멜랑콜리한 감성과 묵직한 리얼악기 사운드가 핵심을 이룹니다.\n\n", '음악적으로는 기타 중심의 록 사운드를 기반으로 하며, 과장된 화려함보다는 멜로디자체의 우아함과 코드의 울림을 중시합니다. 가사에는 영국 사회의 계급 문제, 우울한 날씨, 냉소적인 유머, 개인의 내면적 방황 등 현실적이고 철학적인 주제가 자주 등장합니다. 비틀즈(The Beatles), 퀸(Queen), 오아시스(Oasis), 라디오헤드(Radiohead), 콜드플레이(Coldplay) 등 시대를 대표하는 밴드들은 각기다른색깔을 지녔지만, 정교한 멜로디 라인과 앨범 단위의 높은완성도를 공유한다는 공통점이 있스빈다.\n\n요약 및 차이점\n', "J-Pop이 변칙적이고 극적인 코드 전개와 아기자기한 구성으로 '청각적 쾌감과 서사성'을 극대화한다면, 브리티시 밴드는 기교를 넘어서는 특유의 감성적인 멜로디와 밴드 앙상블, 특유의 어두우면서도 서정적인 분위기로 음악적 깊이를전달합니다."]

In [144]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import time

In [145]:
dv = webdriver.Chrome()
dv.get('https://www.naver.com')
time.sleep(0.5)

el = dv.find_element(By.NAME, "query")
el.send_keys('맞춤법검사기')
el.send_keys(Keys.RETURN)
time.sleep(1)

chk = dv.find_element(By.CLASS_NAME, "txt_gray")
rslts = ''

for idx, ready_text in enumerate(ready_text_list):
    print(f'{idx+1}/{len(ready_text_list)}')
    chk.clear()
    chk.send_keys(ready_text)
    dv.find_element(By.CLASS_NAME, "btn_check").click()
    time.sleep(2)
    rslt = dv.find_element(By.CLASS_NAME, "_result_text").text
    rslts += rslt + '\n'


print('맞춤법 교정 완료')
dv.quit()

1/6
2/6
3/6
4/6
5/6
6/6
맞춤법 교정 완료

In [146]:
with open('data/ch14_맞춤법검사_후.txt', 'w', encoding='utf-8') as f:
    f.write(rslts)

## quiz

In [160]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

with open('data/ch14_맞춤법후.txt', 'r', encoding='utf-8') as fp:
    text = fp.read()

dv = webdriver.Chrome()
dv.get('https://papago.naver.com/')

print('번역기 접속 완료')
time.sleep(1)

close_box = dv.find_element(By.CLASS_NAME, "entry-popup-module-scss-module__UZIxta__close")
close_box.click()

print('파일 번역 진행 중 ...')
time.sleep(1)

chk = dv.find_element(By.CSS_SELECTOR,\
                      "div.text-translator-module-scss-module__CYJRkW__original-textarea > \
                      div.text-editor-module-scss-module__gKzuvW__text-area.text-editor-module-scss-module__gKzuvW__dynamic-md.text-translator-module-scss-module__CYJRkW__text-editor")

chk.send_keys(text)
time.sleep(5)
rslt_list = dv.find_elements(By.CSS_SELECTOR, "div.text-translator-module-scss-module__CYJRkW__has-translation div.text-editor-module-scss-module__gKzuvW__text-area > p > span")

rslts = ''

for rslt in rslt_list:
    rslts += rslt.text + '\n\n'

print('한 → 영 번역 완료')
dv.quit()

with open('data/ch14_자동화영어번역본.txt', 'w', encoding='utf-8') as f:
    f.write(rslts)

번역기 접속 완료
파일 번역 진행 중 ...
한 → 영 번역 완료

- 3000자에 맞춰 파일 정리 및 번역본 출력

In [170]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

# 파일 불러오기
with open('data/ch14_맞춤법후.txt', 'r', encoding='utf-8') as fp:
    text = fp.read()

# 프로그램 규격에 맞추어 파일 정리
ready_text_list = []

while len(text)>=3000:
    print(len(text))
    temp = text[:3000]
    last_dot_index = temp.rfind('\n')
    ready_text_list.append(text[:last_dot_index+1])
    text = text[last_dot_index+1:]
ready_text_list.append(text)
    
# 번역기 접속
dv = webdriver.Chrome()
dv.get('https://papago.naver.com/')

print('번역기 접속 완료')
time.sleep(1)

# 팝업 닫기
close_box = dv.find_element(By.CLASS_NAME, "entry-popup-module-scss-module__UZIxta__close")
if close_box:
    close_box.click()

print('파일 번역 진행 중 ...')
time.sleep(1)

# 텍스트 입력 위치 지정
chk = dv.find_element(By.CSS_SELECTOR,\
                      "div.text-translator-module-scss-module__CYJRkW__original-textarea > \
                      div.text-editor-module-scss-module__gKzuvW__text-area.text-editor-module-scss-module__gKzuvW__dynamic-md.text-translator-module-scss-module__CYJRkW__text-editor")

# 텍스트 입력
rslts = ''

for idx, ready_text in enumerate(ready_text_list):
    print(f'{idx+1}/{len(ready_text_list)}')
    chk.send_keys(Keys.CONTROL, "a")
    chk.send_keys(ready_text)
    time.sleep(5)
    rslt = dv.find_elements(By.CSS_SELECTOR, 'div[class^="text-editor-module-scss-module"]')[1].text
    rslts += rslt + '\n\n'



print('한 → 영 번역 완료')
dv.quit()

with open('data/ch14_자동화영어번역본.txt', 'w', encoding='utf-8') as f:
    f.write(rslts)

번역기 접속 완료
파일 번역 진행 중 ...
1/1
한 → 영 번역 완료